(import (rnrs))
(display 10)
(display " ")
(display (+ 5 3 4))
(display " ")
(display (- 9 1))
(display " ")
(display (/ 6 2))
(display " ")
(display (+ (* 2 4) (- 4 6)))
(display " ")
(define a 3)
(define b (+ a 1))
(display (+ a b (* a b)))
(display " ")
(display (= a b))
(display " ")
(display (if (and (> b a) (< b (* a b)))
	b
	a))
(display " ")
(display (cond ((= a 4) 6)
	((= b 4) (+ 6 7 a))
	(else 25)))
(display " ")
(display (+ 2 (if (> b a) b a)))
(display " ")
(display (* (cond ((> a b) a)
	((< a b) b)
	(else -1))
(+ a 1)))
(display " ")
